repos:
  # Python code formatting and linting with Ruff (replaces black, flake8, isort)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
        types: [python]
      # Run the formatter
      - id: ruff-format
        types: [python]

  # Python type checking with basedpyright (replaces mypy)
  - repo: local
    hooks:
      - id: basedpyright
        name: basedpyright
        entry: basedpyright
        language: system
        types: [python]
        pass_filenames: false
        args: [--outputjson]
        stages: [manual]  # Only run manually due to performance

  # Standard file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: \.md$
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-yaml
      - id: check-json
      - id: check-toml

  # Run critical smoke tests before commit
  - repo: local
    hooks:
      - id: smoke-tests
        name: Critical Smoke Tests
        entry: python
        language: system
        args: [-m, pytest, tests/test_smoke_integration.py::TestProductionSmokeTests::test_production_mainwindow_instantiation, tests/test_smoke_integration.py::TestProductionSmokeTests::test_main_entry_point_imports, -v]
        pass_filenames: false
        stages: [pre-commit]

# Configuration for CI
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_schedule: weekly
  skip: [basedpyright, smoke-tests]  # Skip resource-intensive hooks in CI
