from typing import Any, Callable, TypeVar, Tuple

F = TypeVar('F', bound=Callable[..., Any])

def operation(action_name: str, record_history: bool = True) -> Callable[[F], F]: ...

def confirm_delete(main_window: Any, count: int) -> bool: ...

def normalize_point(point: Tuple[Any, ...]) -> Tuple[Any, ...]: ...

def set_point_status(point: Tuple[Any, ...], status: Any) -> Tuple[Any, ...]: ...
