name: Quick Check

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  quick-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - name: Install dependencies
      run: |
        uv sync

    - name: Run quick tests
      env:
        QT_QPA_PLATFORM: offscreen
      run: |
        # Run only fast tests (no coverage for speed)
        uv run pytest tests/ -x --tb=short -q || true

        # Show summary
        echo "Quick test run completed"
        uv run pytest tests/ --co -q | tail -5
